"use client"

import { useState, useEffect } from "react"
import { ProtectedRoute } from "@/components/protected-route"
import { Navbar } from "@/components/navbar"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Download, TrendingUp, Users, Wallet, Activity, Loader2 } from "lucide-react"
import Link from "next/link"
import { TransactionChart } from "@/components/reports/transaction-chart"
import { useAuth } from "@/lib/auth-context"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { FileText, FileSpreadsheet } from "lucide-react"
import { downloadCSV, downloadExcel, generatePDF, type ExportData } from "@/lib/export-utils"

export default function AnalyticsPage() {
  const { user } = useAuth()
  const [loading, setLoading] = useState(true)
  const [stats, setStats] = useState<any>(null)
  const [customers, setCustomers] = useState<any[]>([])
  const [transactions, setTransactions] = useState<any[]>([])

  useEffect(() => {
    if (user?.id) {
      fetchData()
    }
  }, [user])

  const fetchData = async () => {
    if (!user?.id) return

    try {
      setLoading(true)
      
      // Fetch stats
      const statsResponse = await fetch(`/api/admin/stats?userId=${user.id}`)
      const statsData = await statsResponse.json()
      if (statsData.error) throw new Error(statsData.error)
      setStats(statsData)

      // Fetch customers
      const customersResponse = await fetch(`/api/admin/customers?userId=${user.id}`)
      const customersData = await customersResponse.json()
      if (customersData.error) throw new Error(customersData.error)
      setCustomers(customersData.customers || [])

      // Fetch transactions
      const transactionsResponse = await fetch(`/api/admin/transactions?userId=${user.id}&limit=1000`)
      const transactionsData = await transactionsResponse.json()
      if (transactionsData.error) throw new Error(transactionsData.error)
      setTransactions(transactionsData.transactions || [])
    } catch (error) {
      console.error('Error fetching analytics data:', error)
    } finally {
      setLoading(false)
    }
  }

  if (loading) {
    return (
      <ProtectedRoute allowedRoles={["admin"]}>
        <div className="min-h-screen bg-background">
          <Navbar />
          <main className="container mx-auto px-4 py-8">
            <div className="flex items-center justify-center min-h-[400px]">
              <div className="text-center">
                <Loader2 className="w-8 h-8 animate-spin text-blue-600 dark:text-blue-400 mx-auto mb-4" />
                <p className="text-muted-foreground">Loading analytics...</p>
              </div>
            </div>
          </main>
        </div>
      </ProtectedRoute>
    )
  }

  // Calculate metrics from real data
  const totalCustomers = stats?.totalCustomers || customers.length || 0
  const activeCustomers = stats?.activeCustomers || customers.filter((c) => c.status === "active").length || 0
  const totalBalance = stats?.totalBalance || 0
  const avgBalance = totalCustomers > 0 ? totalBalance / totalCustomers : 0

  // Calculate deposits and withdrawals from real transactions
  const depositTransactions = transactions.filter((t) => t.transaction_type === "deposit" && t.status === "completed")
  const withdrawalTransactions = transactions.filter((t) => t.transaction_type === "withdrawal" && t.status === "completed")
  
  const totalDeposits = stats?.totalDeposits || depositTransactions.reduce((sum, t) => sum + parseFloat(t.amount || 0), 0)
  const totalWithdrawals = stats?.totalWithdrawals || withdrawalTransactions.reduce((sum, t) => sum + parseFloat(t.amount || 0), 0)
  
  const totalTransactions = stats?.totalTransactions || transactions.length || 0
  const depositsCount = stats?.depositsCount || depositTransactions.length
  const withdrawalsCount = stats?.withdrawalsCount || withdrawalTransactions.length

  // Format analytics data for export
  const formatAnalyticsForExport = (): ExportData => {
    const netCashFlow = totalDeposits - totalWithdrawals
    const avgTransactionSize = transactions.length > 0
      ? transactions.reduce((sum, t) => sum + parseFloat(t.amount || 0), 0) / transactions.length
      : 0
    const customerRetention = totalCustomers > 0 ? ((activeCustomers / totalCustomers) * 100).toFixed(1) : 0

    return {
      title: "Analytics & Reports - Financial Summary",
      metadata: {
        "Generated": new Date().toLocaleString(),
        "Report Period": "All Time",
        "Generated By": user?.name || user?.email || "Admin"
      },
      headers: [
        "Metric",
        "Value",
        "Details"
      ],
      rows: [
        ["Total Customers", totalCustomers.toString(), `${activeCustomers} active`],
        ["Total Balance", `$${totalBalance.toLocaleString()}`, "All accounts"],
        ["Average Balance", `$${avgBalance.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, "Per customer"],
        ["Total Transactions", totalTransactions.toString(), "All time"],
        ["Total Deposits", `$${totalDeposits.toLocaleString()}`, `${depositsCount} transactions`],
        ["Total Withdrawals", `$${totalWithdrawals.toLocaleString()}`, `${withdrawalsCount} transactions`],
        ["Net Cash Flow", `$${netCashFlow.toLocaleString()}`, netCashFlow >= 0 ? "Positive flow" : "Negative flow"],
        ["Customer Retention", `${customerRetention}%`, "Active vs Total"],
        ["Average Transaction Size", `$${avgTransactionSize.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, "Per transaction"],
        ["Account Distribution", "", `Checking: ${customers.filter((c) => c.accountType === "checking").length}, Savings: ${customers.filter((c) => c.accountType === "savings").length}, Business: ${customers.filter((c) => c.accountType === "business").length}`]
      ]
    }
  }

  const handleExport = (format: "csv" | "excel" | "pdf") => {
    const exportData = formatAnalyticsForExport()
    const dateStr = new Date().toISOString().split('T')[0]
    const filename = `analytics-report-${dateStr}`

    switch (format) {
      case "csv":
        downloadCSV(exportData, `${filename}.csv`)
        break
      case "excel":
        downloadExcel(exportData, `${filename}.xls`)
        break
      case "pdf":
        generatePDF(exportData, `${filename}.pdf`)
        break
    }
  }

  const statCards = [
    {
      title: "Total Customers",
      value: totalCustomers,
      icon: Users,
      color: "text-blue-600",
      bgColor: "bg-blue-500/10",
      description: `${activeCustomers} active`,
    },
    {
      title: "Total Balance",
      value: `$${totalBalance.toLocaleString()}`,
      icon: Wallet,
      color: "text-green-600",
      bgColor: "bg-green-500/10",
      description: "All accounts",
    },
    {
      title: "Average Balance",
      value: `$${avgBalance.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      icon: TrendingUp,
      color: "text-purple-600",
      bgColor: "bg-purple-500/10",
      description: "Per customer",
    },
    {
      title: "Total Transactions",
      value: totalTransactions,
      icon: Activity,
      color: "text-orange-600",
      bgColor: "bg-orange-500/10",
      description: "All time",
    },
  ]

  return (
    <ProtectedRoute allowedRoles={["admin"]}>
      <div className="min-h-screen bg-background">
        <Navbar />
        <main className="container mx-auto px-4 py-8">
          <div className="flex items-center justify-between mb-8">
            <div>
              <Link href="/admin" className="text-sm text-muted-foreground hover:text-foreground mb-2 inline-block">
                ← Back to Dashboard
              </Link>
              <h1 className="text-4xl font-bold text-balance text-gray-900 dark:text-foreground">Analytics & Reports</h1>
              <p className="text-muted-foreground mt-2">Comprehensive financial analysis and insights</p>
            </div>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
            <Button>
              <Download className="w-4 h-4 mr-2" />
              Export Report
            </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem onClick={() => handleExport("csv")}>
                  <FileText className="w-4 h-4 mr-2" />
                  Export as CSV
                </DropdownMenuItem>
                <DropdownMenuItem onClick={() => handleExport("excel")}>
                  <FileSpreadsheet className="w-4 h-4 mr-2" />
                  Export as Excel
                </DropdownMenuItem>
                <DropdownMenuItem onClick={() => handleExport("pdf")}>
                  <FileText className="w-4 h-4 mr-2" />
                  Export as PDF
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>

          {/* Key Metrics */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
            {statCards.map((stat: any) => {
              const Icon = stat.icon
              return (
                <Card key={stat.title} className="border border-gray-200 dark:border-border">
                  <CardContent className="p-6">
                    <div className="flex items-start justify-between">
                      <div>
                        <p className="text-sm text-muted-foreground mb-1">{stat.title}</p>
                        <p className="text-3xl font-bold mb-1 text-gray-900 dark:text-foreground">{stat.value}</p>
                        <p className="text-xs text-muted-foreground">{stat.description}</p>
                      </div>
                      <div className={`${stat.bgColor} ${stat.color} dark:${stat.color.replace('600', '400')} p-3 rounded-lg`}>
                        <Icon className="w-6 h-6" />
                      </div>
                    </div>
                  </CardContent>
                </Card>
              )
            })}
          </div>

          {/* Financial Overview */}
          <Card className="mb-8 border border-gray-200 dark:border-border">
            <CardHeader>
              <CardTitle className="text-gray-900 dark:text-foreground">Financial Summary</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="space-y-2">
                  <p className="text-sm text-muted-foreground">Total Deposits</p>
                  <p className="text-3xl font-bold text-green-600 dark:text-green-400">${totalDeposits.toLocaleString()}</p>
                  <p className="text-xs text-muted-foreground">
                    {depositsCount} transactions
                  </p>
                </div>
                <div className="space-y-2">
                  <p className="text-sm text-muted-foreground">Total Withdrawals</p>
                  <p className="text-3xl font-bold text-red-600 dark:text-red-400">${totalWithdrawals.toLocaleString()}</p>
                  <p className="text-xs text-muted-foreground">
                    {withdrawalsCount} transactions
                  </p>
                </div>
                <div className="space-y-2">
                  <p className="text-sm text-muted-foreground">Net Cash Flow</p>
                  <p
                    className={`text-3xl font-bold ${
                      totalDeposits - totalWithdrawals >= 0 
                        ? "text-green-600 dark:text-green-400" 
                        : "text-red-600 dark:text-red-400"
                    }`}
                  >
                    ${(totalDeposits - totalWithdrawals).toLocaleString()}
                  </p>
                  <p className="text-xs text-muted-foreground">
                    {totalDeposits - totalWithdrawals >= 0 ? "Positive" : "Negative"} flow
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Charts */}
          <TransactionChart transactions={transactions} />

          {/* Customer Insights */}
          <Card className="mt-8 border border-gray-200 dark:border-border">
            <CardHeader>
              <CardTitle className="text-gray-900 dark:text-foreground">Customer Insights</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex items-center justify-between py-3 border-b border-gray-200 dark:border-border">
                  <div>
                    <p className="font-medium text-gray-900 dark:text-foreground">Account Distribution</p>
                    <p className="text-sm text-muted-foreground">By account type</p>
                  </div>
                  <div className="text-right">
                    <p className="text-sm text-gray-900 dark:text-foreground">
                      Checking: {customers.filter((c) => c.accountType === "checking").length} | Savings:{" "}
                      {customers.filter((c) => c.accountType === "savings").length} | Business:{" "}
                      {customers.filter((c) => c.accountType === "business").length}
                    </p>
                  </div>
                </div>
                <div className="flex items-center justify-between py-3 border-b border-gray-200 dark:border-border">
                  <div>
                    <p className="font-medium text-gray-900 dark:text-foreground">Customer Retention</p>
                    <p className="text-sm text-muted-foreground">Active vs Total</p>
                  </div>
                  <div className="text-right">
                    <p className="text-2xl font-bold text-green-600 dark:text-green-400">
                      {((activeCustomers / totalCustomers) * 100).toFixed(1)}%
                    </p>
                  </div>
                </div>
                <div className="flex items-center justify-between py-3">
                  <div>
                    <p className="font-medium text-gray-900 dark:text-foreground">Average Transaction Size</p>
                    <p className="text-sm text-muted-foreground">Per transaction</p>
                  </div>
                  <div className="text-right">
                    <p className="text-2xl font-bold text-gray-900 dark:text-foreground">
                      $
                      {transactions.length > 0
                        ? (
                            transactions.reduce((sum, t) => sum + parseFloat(t.amount || 0), 0) / transactions.length
                          ).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })
                        : "0.00"}
                    </p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </main>
      </div>
    </ProtectedRoute>
  )
}
